#!/usr/bin/env bash

set -euo pipefail

if [[ ! " $* " == *" -p "* && ! " $* " == *" --package "* ]]; then
    set -- "$@" --workspace
fi

set -x
"${CARGO:-cargo}" clippy "$@" --release --all-targets --all-features -- --deny warnings

# If local, run other checks if we have the tools installed.
if [[ -z "${GITHUB_ACTIONS+x}" ]]; then
    if which cargo-shear >/dev/null 2>&1; then
        cargo shear --locked --deny-warnings
    fi

    if which typos >/dev/null 2>&1; then
        typos --config typos.toml
    fi
fi
